spring:
  mvc:
    servlet: 
      path: /
  application:
    name: videocutbe
  jackson:
    default-property-inclusion: NON_NULL
  
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: validate
      
      
  ##############################################################
  # VIDEOMANAGE DATASOURCE DEFINITION
  #############################################################
  datasource:
    url: ${dbconnection:jdbc:mysql://212.162.68.21:3306/videomanage?autoReconnect=true&useUnicode=true&createDatabaseIfNotExist=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false}
    driverClassName: ${dbdriver:com.mysql.cj.jdbc.Driver}
    username: ${dbusername:videomanage}
    password: ${dbpassword:VIDEOmanage1}
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 10
      minimum-idle: 5
      pool-name: videocutbePool
      connection-timeout: 20000
APP_TITLE: ${APP_TILE:test in ide}